-- -- V13__Create_Table_Permission.sql --
-- CREATE TABLE IF NOT EXISTS `permission` (
--     `id` bigint(20) NOT NULL AUTO_INCREMENT,
--     `description` varchar(255) DEFAULT NULL,
--     PRIMARY KEY (`id`)
--     ) ENGINE=InnoDB;
--
-- -- V15__Create_Table_Users.sql --
-- CREATE TABLE IF NOT EXISTS `users` (
--     `id` bigint(20) NOT NULL AUTO_INCREMENT,
--     `user_name` varchar(255) DEFAULT NULL,
--     `full_name` varchar(255) DEFAULT NULL,
--     `password` varchar(255) DEFAULT NULL,
--     `account_non_expired` bit(1) DEFAULT NULL,
--     `account_non_locked` bit(1) DEFAULT NULL,
--     `credentials_non_expired` bit(1) DEFAULT NULL,
--     `enabled` bit(1) DEFAULT NULL,
--     PRIMARY KEY (`id`),
--     UNIQUE KEY `uk_user_name` (`user_name`)
--     ) ENGINE=InnoDB;
--
-- -- V17__Create_Table_User_Permission.sql --
-- CREATE TABLE IF NOT EXISTS `user_permission` (
--     `id_user` bigint(20) NOT NULL,
--     `id_permission` bigint(20) NOT NULL,
--     PRIMARY KEY (`id_user`,`id_permission`),
--     KEY `fk_user_permission_permission` (`id_permission`),
--     CONSTRAINT `fk_user_permission` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`),
--     CONSTRAINT `fk_user_permission_permission` FOREIGN KEY (`id_permission`) REFERENCES `permission` (`id`)
--     ) ENGINE=InnoDB;